# Agrega tu email y contraseña de LinkedIn.
# *** ADVERTENCIA: MANTÉN ESTA CONFIGURACIÓN OFFLINE EN TU PC Y NO LA SUBAS/CONFIRMES ***
email: email@domain.com
password: yourpassword

# Anti-bloqueo por defecto es False para prevenir que tu PC entre en suspensión y
# permitir que el bot funcione sin interrupciones. Ponlo en True si deseas
# deshabilitar esta funcionalidad.
disableAntiLock: False

# Pon en True si deseas buscar solo trabajos remotos.
remote: False

# Pon en True si deseas buscar trabajos marcados como "menos de 10
# postulantes" (por defecto es False).
lessthanTenApplicants: False

# Pon en True o False según tu preferencia. Se permiten múltiples True.
experienceLevel:
 internship: True
 entry: True
 associate: False
 mid-senior level: False
 director: False
 executive: False

# Pon en True o False según tu preferencia. Se permiten múltiples True.
jobTypes:
 full-time: True
 contract: True
 part-time: False
 temporary: True
 internship: True
 other: False
 volunteer: False

# Pon SOLO uno en True según tu preferencia.
date:
 all time: True
 month: False
 week: False
 24 hours: False

# Quita el signo # para agregar posiciones. Puedes agregar tantas como necesites,
# pero conserva el formato
positions:
 - Ingeniero de Datos Junior
 - Trainee Software Engineer
 - Junior Developer
 - Ingeniero Análisis Datos
 - AI and Automation Engineer
 - Desarrollador Junior 
 - Junior Front-End Software Engineer
 - Junior Cloud Engineer
 - Ingeniero de software 
 - Junior Software Engineer
 - Junior QA Engineer
 - Junior DevOps Engineer
 - Junior Data Scientist
 - Junior Product Manager
 - Junior Data Analyst
 - Junior UX/UI Designer
 - Junior Systems Administrator
 - Junior Network Engineer
 - Junior Backend Developer
 - Junior Frontend Developer
 - Junior Fullstack Developer
 - Junior Mobile Developer
 - Junior Game Developer
 - Junior Security Analyst
 - Junior Data Engineer
 #- A third position
 #- A third position
 #- A third position
 #- A third position
 #- A third position
 #- A third position
 #- A third position 
 #- A third position

 #- ...

# Quita el signo # para agregar ubicaciones. Puedes agregar tantas como necesites
# incluyendo agregar 'Remote' como ubicación pero la primera ubicación debe ser
# un país válido.
locations: 
 - Colombia
 - United States
 - Canada
 - Spain
 - Germany
 - France
 - Italy
 - Netherlands
 - Australia
 - Switzerland
 #- A third location
 #- A third location
 #- A third location
 #- A third location
 #- ...
 - Remote

# Pon en True si estás residiendo en el país del trabajo
residentStatus: False

# Distancia desde la ubicación agregada arriba. Valores permitidos son
# {0, 5, 10, 25, 50, 100}, usa solo uno.
distance: 100

# Directorio opcional para guardar logs, no funciona a veces.
# No funciona a veces, así que déjalo sin cambios.
outputFileDirectory: ~/Documents/Applications/EasyApplyBot/EasyApplyBot/

# Empresas a las que no quieres postularte.
companyBlacklist:
 - BairesDev
 - Truora Inc
 - Micro Talent
 - FullStack Labs
 - EPAM Systems
 #- company2

# Títulos de trabajo que quieres evitar. Úsalo para refinar el rendimiento del bot.
titleBlacklist:
 - Sales Executive
 - Tecnico de Mantenimiento Industrial
 - General Practitioner
 - Coordinador de Procesos
 - Accountant
 - Gerente de Recursos Humanos
 - Civil Engineer
 - Graphic Designer
 - Chef de Cocina
 - Enfermero
 - Lawyer
 - Arquitecto
 - Retail Manager
 - Soldador
 - Marketing Specialist
 - Asesor Financiero
 - Agente Inmobiliario
 - Customer Service Manager
 - Biologist
 - Asistente Administrativo
 - Recruiter
 - Chemical Engineer
 - Plumber
 - Geologist
 #- word2
 #- word2
 #- word2
 #- word2
 #- word2
 #- word2

# El bot no se postulará a trabajos publicados por personas en lista negra.
posterBlacklist:
 #- name1
 #- name2

# Ruta a tu CV/currículum y carta de presentación (quita el signo #). Estas
# rutas a menudo no funcionan así que postúlate a un trabajo manualmente una vez,
# el bot reutilizará el CV subido manualmente para automatizar la tarea. Nota: Prefiere
# una ruta sin espacios, ej. en lugar de "Mi Directorio" usa "MiDirectorio" o "Mi_Directorio".
uploads:
 resume: C:\Users\myDirectory\Resume.pdf
 # La carta de presentación es opcional
 #coverLetter: C:\Users\myDirectory\CoverLettter.pdf


# ------------ Sección QA -------------------

# ------------ Parámetros adicionales: casillas de verificación ---------------
checkboxes:
 # ¿Tienes una licencia de conducir válida? (casilla sí/no)
 driversLicence: False
 # ¿Necesitarás ahora o en el futuro patrocinio para
 # estatus de visa de empleo (ej. estatus de visa H-1B)? (casilla sí/no)
 # Esto es relativo a la ubicación y tu ciudadanía postulándote
 # arriba, y lo mismo con legallyAuthorized.
 requireVisa: True
 # ¿Estás legalmente autorizado para trabajar en PAÍS? (casilla sí/no)
 legallyAuthorized: True
 # ¿Tienes las licencias o certificaciones necesarias requeridas en tu
 # profesión? Ej. CPA, CA, CFA, licencia profesional
 certifiedProfessional: True
 # Debemos llenar esta posición urgentemente. ¿Puedes empezar inmediatamente?
 # (casilla sí/no)
 urgentFill: True
 # ¿Te sientes cómodo viajando diariamente o trabajando en el sitio de este trabajo?
 # (casilla sí/no)
 commute: True
 # ¿Te sientes cómodo trabajando en un ambiente remoto? (casilla sí/no)
 remote: True
 # ¿Te sientes cómodo tomando una prueba de drogas de acuerdo con las leyes locales/estatales?
 # (casilla sí/no)
 drugTest: True
 # ¿Estás dispuesto a completar una evaluación? (casilla sí/no)
 assessment: True
 # ¿Tienes autorización de seguridad del país [xxx]? (casilla sí/no)
 securityClearance: False
 # ¿Has completado el siguiente nivel de educación: TIPO DE GRADO? Quita los
 # signos # aplicables (casilla sí/no)
 degreeCompleted:
   - High School Diploma
   - Bachelor's Degree
  # - Associate's Degree
  # - Master's Degree
  # - Master of Business Administration
  # - Doctor of Philosophy
  # - Doctor of Medicine
  # - Doctor of Law
 # ¿Estás dispuesto a someterte a una verificación de antecedentes, de acuerdo con las
 # leyes/regulaciones locales?
 backgroundCheck: True

# ------------ Parámetros adicionales: universityGpa ---------------
universityGpa: 4.0

# ------------ Parámetros adicionales: salaryMinimum ---------------
salaryMinimum: 1200

# ------------ Parámetros adicionales: idiomas ---------------
languages:
 english: Professional # Opciones permitidas { None, Conversational, Professional, Native or bilingual }
 spanish: Native or bilingual
 # arabic: Conversational
 # french: Professional

# ------------ Parámetros adicionales: noticePeriod en semanas ---------------
noticePeriod: 2

# ------------ Parámetros adicionales: años de experiencia ---------------
# ¿Cuántos años de experiencia laboral tienes...? (solo números enteros).
# Puedes agregar más habilidades dependiendo de tu industria o profesión al final.
# Usa `unprepared questions.csv` para agregar más dependiendo de tu caso de uso.
# Algunas muestras se agregan abajo, puede que no necesites todas estas. El valor 'default'
# será usado como entrada de respaldo para preguntas adicionales.
experience:
 # normales
 Accounting/Auditing: 0
 Administrative : 0
 Advertising : 0
 Analyst : 0
 Art/Creative: 0
 Business Development: 0
 Consulting: 0
 Customer Service: 0
 Distribution Design: 0
 Education: 0
 Engineering: 1
 Finance: 0
 General Business: 0
 Health Care Provider: 0
 Human Resources: 0
 Information Technology: 0
 Legal: 0
 Management: 0
 Manufacturing: 0
 Marketing: 0
 Public Relations: 0
 Purchasing: 0
 Product Management: 0
 Project Management: 0
 Production: 0
 Quality Assurance: 0
 Research: 0
 Sales: 0
 Science: 0
 Strategy/Planning: 0
 Supply Chain: 0
 Training: 0
 Writing/Editing: 0
 VBA: 0
 PowerBI: 1
 PowerQuery: 0
 Excel: 1
 PowerPoint: 1
 Word: 1
 SQL Server: 1
 Communication: 0
 Financial markets: 0
 Business: 0
 Financial services: 0
 Team leadership: 0
 Cash flow: 0
 Hedging: 0
 Treasury services: 0
 Microsoft Power BI: 1
 Accounting: 0
 Auditing: 0
 Financial modeling: 0
 Budgeting & forecasting: 0
 FP&A: 0
 PQE: 0
 Training & Development: 0
 python: 1
 SQL: 1
 Cloud: 1
 ETL: 1
 HTML: 1
 CSS: 1
 JavaScript: 1
 React: 1
 Astro: 1
 Angular: 1
 Vue.js: 1
 Node.js: 1
 APIs RESTful: 1
 Django: 1
 Flask: 1
 PostgreSQL: 1
 MySQL: 1
 MongoDB: 1
 AWS: 1
 Azure: 1
 GCP: 1
 Docker: 1
 Jenkins: 1
 GitHub Actions: 1
 Terraform: 1
 Postman: 1
 Flutter: 1
 TensorFlow: 1
 PyTorch: 1
 Desarrollo de aplicaciones móviles: 1
 Mobile Application Development: 1
 Production Deployments: 1
 AWS Debugging: 8  # Escala del 1-10, ajusta según tu nivel real
 AWS Production Issues: 8
 Documentación Técnica: 1  # Ajusta este valor según tu experiencia real (0-99)
 Technical Documentation: 1
 ML: 1  # Machine Learning experience
 Machine Learning: 1
 SQL: 1
 sql: 1
 base de datos: 1
 base de datos sql: 1
 ETL: 1
 etl: 1
 extraer transformar cargar: 1
 distribución: 1  # Ajusta este valor según tu experiencia real (0-99)
 distributoría: 1
 distribution: 1
 amazon web services: 1
 microservicios: 1
 microservices: 1
 .net: 1
 .net apis: 1
 net apis: 1
 apis: 1
 VUE: 1
 Vue: 1
 vue: 1
 Python: 1
 .Net: 1





 #selenium: 0
 # por defecto para poner en cualquier industria/habilidad que no listaste
 default: 0

# ------------ Parámetros adicionales: información personal ---------------
personalInfo:
 Pronouns: Mr.
 First Name: FirstName
 Last Name: LastName
 Phone Country Code: Canada (+1) # Ve LinkedIn para el código de tu país, debe ser exacto según la plataforma internacional, ej. Italy (+39) no Italia (+39)
 Mobile Phone Number: 1234567890
 Street address: 123 Fake Street
 City: Red Deer, Alberta # ¡Incluye también el estado/provincia!
 State: YourState
 Zip: YourZip/Postal
 Linkedin: https://www.linkedin.com/in/my-linkedin-profile
 Website: https://www.my-website.com # github/website son intercambiables aquí
 MessageToManager: "Hi, I am interested to join your organization. Please have a look at my resume. Thank you." # Mantén el mensaje corto y entre comillas. Esta es una función de prueba y puede no funcionar.

# ------------ Parámetros adicionales: porquerías de empleo de USA ---------------
eeo:
 gender: None
 race: None
 veteran: None
 disability: None
 citizenship: yes
 clearance: no
